name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Use case / motivation
    validations:
      required: true
